// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	BOT_TOKEN: "bot_token";
	WORK_REPORTER_APP: "work_reporter_app";
	DB: D1Database;
}
